### ISSUE TITLE
Smart Uploading and Downloading Require

### ISSUE THREAD

**Issue by lrmalaysia** [internxt/drive-web#268]
I deleted a file but sync process still downloading other files. Somehow my computer went off due to long idle time caused the sync disconnected. After connect back to drive it download the deleted file instead of remove it from web drive. Secondly, I do nothing with the synced files but when sync it show downloading and uploading process for the files again.

I deleted the file on A computer (Mac) and synced to the drive then B computer (Windows) sync will upload the file again instead of remove it. Sync again with A computer (Mac) then it download the file again. This sync definitely need improvement. Not sure how about edit documents.

**Comment by AlexMenor** [comment]
Hi @lrmalaysia, there are two kinds of sync processes that can happen:
- With no previous state
- With previous state

The first one executes if it is the first sync process or if the last sync wasn't successful (local and remote are not in sync in the end).

As the first one has no state, it has no way to know if a file has been deleted or if it has been added to one of the sides.

**Comment by lrmalaysia** [comment]
> Hi @lrmalaysia, there are two kinds of sync processes that can happen:
> 
> * With no previous state
> * With previous state
> 
> The first one executes if it is the first sync process or if the last sync wasn't successful (local and remote are not in sync in the end).
> 
> As the first one has no state, it has no way to know if a file has been deleted or if it has been added to one of the sides.

But this is no way to set right? I just open the app and click Sync. As mentioned, after synced Computer A then I synced Computer B. After everything synced, I deleted some file on Computer A and synced Computer A. Web Drive file deleted. 

I go back to Computer B click sync, it upload the file instead of delete it. So the whole synchronization seem like not working well if sync with 2 devices.

Another case is I do nothing with the synced files but when clicked sync it show downloading and uploading process for the files again.

**Comment by AlexMenor** [comment]
If the Computer B had its last sync done succesfully, it would have deleted the file. But as it was not succesful (perhaps you stopped it in the middle), it has no way to know if that file was deleted or if it was added to Computer B.

I hope its clear

**Comment by lrmalaysia** [comment]
> If the Computer B had its last sync done succesfully, it would have deleted the file. But as it was not succesful (perhaps you stopped it in the middle), it has no way to know if that file was deleted or if it was added to Computer B.
> 
> I hope its clear

Yes, both sync completed with everything are the same. Then I delete some file on Computer A click synced until complete. I back to Computer B click sync again then the whole process as describe happened. Anyway, is not possible to synced both in the same time. Only one sync completed can only click another sync. 

I try to do this is want to confirm everything is working. I try to use it on December time which is more terrible. After synced Computer A. Computer B sync and stop half way. Click sync again it download and upload the synced file with ".local" ".remote" then I decided to opt out. Now I have free time so try it again with some testing. Unfortunately it still not working well.

**Comment by AlexMenor** [comment]
Are you sure that Computer B has no sync issues (a little red notification over the settings icon)?

**Comment by lrmalaysia** [comment]
> Are you sure that Computer B has no sync issues (a little red notification over the settings icon)?

Yes, completed without any error. It synced and stop automatically. After that I go to delete some files on Computer A and start the sync until it stop automatically. Go to web drive and check file removed. Then back to Computer B click the play button to sync again. Removed files uploaded instead remove from my Computer B. As mentioned Computer A is MacOS. Computer B is Windows 11.

**Comment by AlexMenor** [comment]
Can you please try to reproduce it again?
- Sync both computers
- Remove file in Computer A
- Sync computer A
- Sync computer B

I am not able to reproduce this issue doing this

**Comment by lrmalaysia** [comment]
> Can you please try to reproduce it again?
> 
> * Sync both computers
> * Remove file in Computer A
> * Sync computer A
> * Sync computer B
> 
> I am not able to reproduce this issue doing this

Yes, reproduced easily. All the print screen as below. Maybe you need try between MacOS and Windows.

https://siasky.net/nADZcuzfEWyM36yIGqkotd3F__lAmNtLHmxBdWtp9xBUcQ

**Comment by AlexMenor** [comment]
Can you please send me the logs to alex (at) internxt (dot) com?

**Comment by lrmalaysia** [comment]
> Can you please send me the logs to alex (at) internxt (dot) com?
> 
> You can find them in the settings window

Okay. By the way, I think I found the problem. Anything Upload from MacOS and deleted from MacOS it will synced to web drive but sync again with windows it will upload to web drive again. But files Uploaded by windows and delete it. It will be permanently removed on both.

**Comment by AlexMenor** [comment]
Yeah, I think that the computer with MacOS is not completely in sync. 
I will know for sure when I see the logs.

Thanks for your help by the way

**Comment by MarvinMep** [comment]
The same happens to me. Actually, it can be observed not only with two devices, but with a computer and the web app <https://drive.internxt.com/app>. The only way I can delete a file is deleting it at the same time on both (file manager and web app). But there's no use, if I access the drive on another computer (a 3rd device) the file comes back to all of them, when the 3rd device syncs (it uploads the file, when it is expected to delete the file).

**Comment by MarvinMep** [comment]
The same is true when moving files or folders. They end up duplicated. This behavior is prohibitive, I can't use the service.

I forgot to mention, I'm using Internxt 1.8 on Debian testing and drive.internxt.com/app (I use it on Debian stable on another divice and android 12 app).

**Comment by MarvinMep** [comment]
There are similar issues, i.e. https://github.com/internxt/drive-desktop/issues/104
